import type { IMovie } from "../types/movie.interface";

export const MOVIES: IMovie[] = [
    {
        title: 'Narcos',
        image: '/narcos.png',
        imageForTrends: '/narcos2.png',
        rating: 8.8,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'xl8zdCY-abw',
        duration: '24h 30m',
        genre: ['Drama', 'Crime'],
        shortDescription: 'The chronicle of the rise and fall of Pablo Escobar and the Medellin cartel, told through the prism of agents of the U.S. Drug Enforcement Administration.',
        description: 'Narcos is an American television drama series created by Chris Brancato, Carlo Bernard and Doug Miro and directed by Brazilian filmmaker José Padilha. The show is a Netflix original series based on the story of Pablo Escobar, as well as the rise of other drug cartels. The series spans three seasons and offers a gritty, realistic portrayal of the war on drugs in Colombia, featuring compelling characters and intense storytelling that has earned it critical acclaim worldwide.'
    },
    {
        title: 'Final Space',
        image: '/final.png',
        imageForTrends: '/final2.png',
        rating: 7.8,
        recommend: true,
        type: 'serial',
        tags: ['popular'],
        trailerYouTubeId: '4EHbt_kSkG8',
        duration: '13h 11m',
        genre: ['Adventure', 'Fantasy', 'Comedy'],
        shortDescription: 'A failed astronaut and his mysterious alien friend accidentally unleash evil on a universal scale and are forced to save the galaxy.',
        description: 'Final Space was an adult-animated series created by Olan Rogers that originally ran on TBS before transferring over to [adult swim], running for 3 seasons from 2018 to 2021 when it was tragically cancelled. The series follows astronaut Gary Goodspeed and his alien friend Mooncake as they navigate through space while confronting cosmic threats. Despite its cancellation, the show developed a cult following and creator Olan Rogers announced that a graphic novel entitled Final Space: The Final Chapter would release in late 2025 to serve as the proper finale for the series.'
    },
    {
        title: 'Rampage',
        image: '/rampage2.png',
        imageForTrends: '/rampage.png',
        rating: 9.8,
        recommend: true,
        type: 'film',
        tags: ['popular'],
        trailerYouTubeId: '4EHbt_kSkG8',
        duration: '1h 47m',
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        shortDescription: 'When three different animals become infected with a dangerous pathogen a primatologist and a geneticist team up to stop them from destroying Chicago.',
        description: 'Rampage is a 2018 American science fiction monster film directed by Brad Peyton and loosely based on the video game series of the same name by Midway Games. The film stars Dwayne Johnson as primatologist Davis Okoye, who teams up with geneticist Dr. Kate Caldwell (Naomie Harris) to stop three genetically mutated animals—a wolf, a crocodile, and Davis\'s beloved albino gorilla George—from destroying Chicago. The film combines spectacular visual effects with thrilling action sequences, delivering an entertaining monster movie experience.'
    },
    {
        title: 'Stranger Things',
        image: '/stranger-things.png',
        imageForTrends: '/stranger-things2.png',
        rating: 8.7,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'b9EkMc79ZSU',
        duration: '51h 45m',
        genre: ['Drama', 'Fantasy', 'Horror'],
        shortDescription: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.',
        description: 'Stranger Things is an American science fiction horror drama television series created by the Duffer Brothers. Set in the 1980s in the fictional town of Hawkins, Indiana, the series follows a group of friends who witness supernatural forces and secret government exploits. They search for missing friends while battling terrifying monsters from an alternate dimension called the Upside Down. The show has become a cultural phenomenon, praised for its character development, tone, homages to 1980s pop culture, and outstanding performances from its ensemble cast.'
    },
    {
        title: 'The Dark Knight',
        image: '/dark-knight.png',
        imageForTrends: '/dark-knight2.png',
        rating: 9.0,
        recommend: true,
        type: 'film',
        tags: ['popular'],
        trailerYouTubeId: 'EXeTwQWrcwY',
        duration: '2h 32m',
        genre: ['Action', 'Crime', 'Drama'],
        shortDescription: 'Batman faces the Joker, a criminal mastermind who seeks to undermine order and create chaos in Gotham City.',
        description: 'The Dark Knight is a 2008 superhero film directed by Christopher Nolan from a screenplay he co-wrote with his brother Jonathan. Based on the DC Comics character Batman, it is the second installment in Nolan\'s The Dark Knight Trilogy and the sequel to Batman Begins. Christian Bale reprises his role as Bruce Wayne/Batman, with Heath Ledger delivering an iconic, Oscar-winning performance as the Joker. The film explores themes of chaos, order, and morality while featuring some of the most memorable action sequences and character dynamics in superhero cinema history.'
    },
    {
        title: 'The Crown',
        image: '/crown.png',
        imageForTrends: '/crown2.png',
        rating: 8.6,
        recommend: false,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'JWtnJjn6ng0',
        duration: '60h 10m',
        genre: ['Biography', 'Drama', 'History'],
        shortDescription: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
        description: 'The Crown is a historical drama television series about the reign of Queen Elizabeth II, created and principally written by Peter Morgan. The show traces the life of Queen Elizabeth II from her wedding in 1947 to the early 21st century. Each season covers approximately one decade of her reign, with the cast changing every two seasons to reflect the aging of the characters. The series has received widespread critical acclaim for its writing, acting, direction, cinematography, and production values, winning numerous awards including Golden Globes and Primetime Emmy Awards.'
    },
    {
        title: 'Inception',
        image: '/inception.png',
        imageForTrends: '/inception2.png',
        rating: 8.8,
        recommend: true,
        type: 'film',
        tags: ['popular'],
        trailerYouTubeId: 'YoHD9XEInc0',
        duration: '2h 28m',
        genre: ['Action', 'Sci-Fi', 'Thriller'],
        shortDescription: 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a C.E.O.',
        description: 'Inception is a 2010 science fiction action film written and directed by Christopher Nolan, who also produced the film with his wife, Emma Thomas. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another person\'s idea into a target\'s subconscious. The film\'s ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Elliot Page, Tom Hardy, Cillian Murphy, Tom Berenger, and Michael Caine.'
    },
    {
        title: 'Breaking Bad',
        image: '/breaking-bad.png',
        imageForTrends: '/breaking-bad2.png',
        rating: 9.5,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'HhesaQXLuRY',
        duration: '62h 10m',
        genre: ['Crime', 'Drama', 'Thriller'],
        shortDescription: 'A high school chemistry teacher diagnosed with cancer turns to manufacturing and selling methamphetamine to secure his family\'s future.',
        description: 'Breaking Bad is an American neo-Western crime drama television series created and produced by Vince Gilligan. Set and filmed in Albuquerque, New Mexico, the series follows Walter White (Bryan Cranston), a struggling, frustrated high school chemistry teacher who is diagnosed with inoperable lung cancer. Together with his former student Jesse Pinkman (Aaron Paul), White turns to a life of crime, producing and distributing methamphetamine to secure his family\'s financial future before he dies. The show is noted for its storytelling, direction, acting, and character development, and is widely regarded as one of the greatest television series of all time.'
    },
    {
        title: 'The Mandalorian',
        image: '/mandalorian.png',
        imageForTrends: '/mandalorian2.png',
        rating: 8.7,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'aOC8E8z_ifw',
        duration: '24h 30m',
        genre: ['Action', 'Adventure', 'Fantasy'],
        shortDescription: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
        description: 'The Mandalorian is an American space Western television series created by Jon Favreau for the streaming service Disney+. It is the first live-action series in the Star Wars franchise, beginning five years after the events of Return of the Jedi. The series stars Pedro Pascal as the title character, a lone bounty hunter who goes on the run to protect "The Child" (nicknamed "Baby Yoda" by fans). The series has been praised for its storytelling, visual effects, musical score, and performances, particularly those of Pascal and the various actors who provide the voice and physical performance for Baby Yoda.'
    },
    {
        title: 'Parasite',
        image: '/parasite.png',
        imageForTrends: '/parasite2.png',
        rating: 8.6,
        recommend: false,
        type: 'film',
        tags: ['trend', 'popular', 'premiere'],
        trailerYouTubeId: '5xH0HfJHsaY',
        duration: '2h 12m',
        genre: ['Comedy', 'Drama', 'Thriller'],
        shortDescription: 'A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.',
        description: 'Parasite is a 2019 South Korean black comedy thriller film directed by Bong Joon-ho, who also co-wrote the screenplay with Han Jin-won. The film follows a poor family who scheme to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals. The film stars Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik, Park So-dam, Jang Hye-jin, and Lee Jung-eun. Parasite made history by becoming the first non-English language film to win the Academy Award for Best Picture, and also won Best Director, Best Original Screenplay, and Best International Feature Film.'
    },
    {
        title: 'Game of Thrones',
        image: '/got.png',
        imageForTrends: '/got2.png',
        rating: 9.2,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'rlR4PJn8b8I',
        duration: '70h 14m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
        description: 'Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, George R. R. Martin\'s series of fantasy novels. Set on the fictional continents of Westeros and Essos, Game of Thrones has several plots and a large ensemble cast and follows several story arcs. One arc is about the Iron Throne of the Seven Kingdoms and follows a web of alliances and conflicts among the noble dynasties either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm\'s deposed ruling dynasty who has been exiled and is plotting a return to the throne.'
    },
    {
        title: 'Interstellar',
        image: '/interstellar.png',
        imageForTrends: '/interstellar2.png',
        rating: 8.6,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular', 'premiere'],
        trailerYouTubeId: 'zSWdZVtXT7E',
        duration: '2h 49m',
        genre: ['Adventure', 'Drama', 'Sci-Fi'],
        shortDescription: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        description: 'Interstellar is a 2014 epic science fiction film directed by Christopher Nolan, who wrote the screenplay with his brother Jonathan. Set in a dystopian future where humanity is struggling to survive, the film follows a group of astronauts who travel through a wormhole near Saturn in search of a new home for humanity. The film stars Matthew McConaughey, Anne Hathaway, Jessica Chastain, Bill Irwin, Ellen Burstyn, Michael Caine, and Matt Damon. Interstellar was praised for its scientific accuracy, visual effects, musical score, and emotional depth, exploring themes of love, time, and human survival.'
    },
    {
        title: 'The Witcher',
        image: '/witcher.png',
        imageForTrends: '/witcher2.png',
        rating: 8.2,
        recommend: true,
        type: 'serial',
        tags: ['popular'],
        trailerYouTubeId: 'ndl1W4ltcmg',
        duration: '24h 15m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.',
        description: 'The Witcher is a fantasy drama streaming television series created by Lauren Schmidt Hissrich for Netflix. It is based on the book series of the same name by Polish writer Andrzej Sapkowski. Set on a fictional, medieval-inspired landmass known as "the Continent", The Witcher explores the legend of Geralt of Rivia and Princess Ciri, who are linked by destiny. The series stars Henry Cavill as Geralt of Rivia, Anya Chalotra as Yennefer of Vengerberg, and Freya Allan as Ciri. It has been praised for its production values, action sequences, and Cavill\'s performance, though it has received mixed reviews for its narrative structure.'
    },
    {
        title: 'Avengers: Endgame',
        image: '/endgame.png',
        imageForTrends: '/endgame2.png',
        rating: 8.4,
        recommend: false,
        type: 'film',
        tags: ['popular'],
        trailerYouTubeId: 'TcMBFSGVi1c',
        duration: '3h 2m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos\' actions and restore balance to the universe.',
        description: 'Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse the damage caused by Thanos in Infinity War.'
    },
    {
        title: 'The Queen\'s Gambit',
        image: '/queens-gambit.png',
        imageForTrends: '/queens-gambit2.png',
        rating: 8.5,
        recommend: true,
        type: 'serial',
        tags: ['popular'],
        trailerYouTubeId: 'CDrieqwSdgI',
        duration: '6h 47m',
        genre: ['Drama'],
        shortDescription: 'Orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest chess player in the world.',
        description: 'The Queen\'s Gambit is a 2020 American coming-of-age period drama streaming television miniseries based on the 1983 novel of the same name by Walter Tevis. The title refers to a chess opening. The series follows the life of an orphan chess prodigy, Beth Harmon, during her quest to become the world\'s greatest chess player while struggling with emotional problems and drug and alcohol dependency. The series stars Anya Taylor-Joy as Beth Harmon, with Bill Camp, Moses Ingram, and Harry Melling in supporting roles. It received widespread critical acclaim for its writing, direction, cinematography, production values, and Taylor-Joy\'s performance.'
    },
    {
        title: 'Dune',
        image: '/dune.png',
        imageForTrends: '/dune2.png',
        rating: 8.0,
        recommend: false,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: '8g18jFHCLXk',
        duration: '2h 35m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'Feature adaptation of Frank Herbert\'s science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset.',
        description: 'Dune is a 2021 American epic science fiction film directed by Denis Villeneuve from a screenplay by Villeneuve, Jon Spaihts, and Eric Roth. It is the first of a two-part adaptation of the 1965 novel of the same name by Frank Herbert. Set in the distant future, the film follows Paul Atreides as his family, the noble House Atreides, is thrust into a war for the deadly and inhospitable desert planet Arrakis. The film stars Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård, Dave Bautista, Zendaya, and Jason Momoa. The film has been praised for its visual effects, sound design, score, and faithfulness to the source material.'
    },
    {
        title: 'Squid Game',
        image: '/squid-game.png',
        imageForTrends: '/squid-game2.png',
        rating: 8.0,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'oqxAJKy0ii4',
        duration: '8h 15m',
        genre: ['Action', 'Drama', 'Mystery'],
        shortDescription: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
        description: 'Squid Game is a South Korean survival drama streaming television series created by Hwang Dong-hyuk for Netflix. The series revolves around a contest where 456 players, all of whom are in deep financial debt, risk their lives to play a series of deadly children\'s games for the chance to win a ₩45.6 billion prize. The series\' title draws from a similarly named Korean children\'s game. It stars Lee Jung-jae, Park Hae-soo, Wi Ha-joon, Jung Ho-yeon, O Yeong-su, Heo Sung-tae, Anupam Tripathi, and Kim Joo-ryoung. The series has received critical acclaim for its social commentary, storyline, cinematography, and performances.'
    },
    {
        title: 'The Matrix',
        image: '/matrix.png',
        imageForTrends: '/matrix2.png',
        rating: 8.7,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular', 'premiere'],
        trailerYouTubeId: 'vKQi3bBA1y8',
        duration: '2h 16m',
        genre: ['Action', 'Sci-Fi'],
        shortDescription: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        description: 'The Matrix is a 1999 science fiction action film written and directed by the Wachowskis. It is the first installment in the Matrix film series, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano. It depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source. When computer programmer Thomas Anderson, under the hacker alias "Neo", uncovers the truth, he "is drawn into a rebellion against the machines" along with other people who have been freed from the Matrix.'
    },
    {
        title: 'Chernobyl',
        image: '/chernobyl.png',
        imageForTrends: '/chernobyl2.png',
        rating: 9.4,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 's9APLXM9Ei8',
        duration: '5h 30m',
        genre: ['Drama', 'History', 'Thriller'],
        shortDescription: 'In April 1986, an explosion at the Chernobyl nuclear power plant becomes one of the world\'s worst man-made catastrophes.',
        description: 'Chernobyl is a 2019 historical drama television miniseries created and written by Craig Mazin and directed by Johan Renck. The series revolves around the Chernobyl nuclear disaster of April 1986 and the cleanup efforts that followed. It features an ensemble cast led by Jared Harris, Stellan Skarsgård, Emily Watson, and Paul Ritter. The series was praised for its acting, directing, writing, and historical accuracy, although some details were criticized by historians. Chernobyl has been described as one of the greatest television miniseries ever made and won numerous awards, including ten Primetime Emmy Awards.'
    },
    {
        title: 'La La Land',
        image: '/lalaland.png',
        imageForTrends: '/lalaland2.png',
        rating: 8.0,
        recommend: false,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: '0pdqf4P9MB8',
        duration: '2h 8m',
        genre: ['Comedy', 'Drama', 'Music'],
        shortDescription: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
        description: 'La La Land is a 2016 American musical romantic comedy-drama film written and directed by Damien Chazelle. It stars Ryan Gosling as a jazz pianist and Emma Stone as an aspiring actress, who meet and fall in love while pursuing their dreams in Los Angeles. The film\'s title refers both to the city of Los Angeles and to the idiom for being out of touch with reality. The film was a critical and commercial success, grossing $448 million worldwide against a production budget of $30 million. It received a record-tying 14 Academy Award nominations, winning six, including Best Director for Chazelle and Best Actress for Stone.'
    },
    {
        title: 'House of the Dragon',
        image: '/hotd.png',
        imageForTrends: '/hotd2.png',
        rating: 8.5,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'DotnJ7tTA34',
        duration: '10h 15m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'The story of the Targaryen civil war that took place about 200 years before events portrayed in "Game of Thrones."',
        description: 'House of the Dragon is an American fantasy drama television series created by Ryan J. Condal and George R. R. Martin for HBO. It is a prequel to Game of Thrones (2011–2019) and is based on parts of Martin\'s 2018 novel Fire & Blood. The series is set about 200 years before the events of Game of Thrones and 172 years before the birth of Daenerys Targaryen. It chronicles the beginning of the end of House Targaryen, the events leading up to and covering the Targaryen war of succession, known as the "Dance of the Dragons". The series stars Paddy Considine, Matt Smith, Olivia Cooke, Emma D\'Arcy, Steve Toussaint, Eve Best, and Rhys Ifans.'
    },
    {
        title: 'John Wick',
        image: '/john-wick.png',
        imageForTrends: '/john-wick2.png',
        rating: 7.4,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'C0BMx-qxsP4',
        duration: '1h 41m',
        genre: ['Action', 'Crime', 'Thriller'],
        shortDescription: 'An ex-hitman comes out of retirement to track down the gangsters who killed his dog and stole his car.',
        description: 'John Wick is a 2014 American neo-noir action thriller film directed by Chad Stahelski, in his directorial debut, and written by Derek Kolstad. It stars Keanu Reeves, Michael Nyqvist, Alfie Allen, Adrianne Palicki, Bridget Moynahan, Dean Winters, Ian McShane, John Leguizamo, and Willem Dafoe. The film follows John Wick (Reeves), a retired hitman seeking vengeance for the killing of the dog given to him by his recently deceased wife and the theft of his car. The film was praised for its stylish action sequences, world-building, and Reeves\' performance, spawning a media franchise with three sequels and various other media.'
    },
    {
        title: 'Black Mirror',
        image: '/black-mirror.png',
        imageForTrends: '/black-mirror2.png',
        rating: 8.8,
        recommend: true,
        type: 'serial',
        tags: ['popular'],
        trailerYouTubeId: 'jROLrhQkK78',
        duration: '45h 20m',
        genre: ['Drama', 'Sci-Fi', 'Thriller'],
        shortDescription: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
        description: 'Black Mirror is a British anthology television series created by Charlie Brooker. Individual episodes explore a diversity of genres, but most are set in near-future dystopias with sci-fi technology—a type of speculative fiction. The series is inspired by The Twilight Zone and uses technology to comment on contemporary social issues. Most episodes are written by Brooker, with heavy involvement by the executive producer Annabel Jones. The series premiered on Channel 4 in December 2011, and moved to Netflix in 2016. Black Mirror has received critical acclaim and has seen an increase in popularity internationally. In 2019, an interactive film titled Black Mirror: Bandersnatch was released.'
    },
    {
        title: 'Spider-Man: No Way Home',
        image: '/spiderman.png',
        imageForTrends: '/spiderman2.png',
        rating: 8.2,
        recommend: false,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'JfVOs4VSpmA',
        duration: '2h 28m',
        genre: ['Action', 'Adventure', 'Fantasy'],
        shortDescription: 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help, unleashing the multiverse.',
        description: 'Spider-Man: No Way Home is a 2021 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing. It is the sequel to Spider-Man: Homecoming (2017) and Spider-Man: Far From Home (2019), and the 27th film in the Marvel Cinematic Universe (MCU). The film was directed by Jon Watts, written by Chris McKenna and Erik Sommers, and stars Tom Holland as Peter Parker / Spider-Man, alongside Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Jamie Foxx, Willem Dafoe, Alfred Molina, Benedict Wong, Tony Revolori, and Marisa Tomei.'
    },
    {
        title: 'Peaky Blinders',
        image: '/peaky.png',
        imageForTrends: '/peaky2.png',
        rating: 8.8,
        recommend: true,
        type: 'serial',
        tags: ['popular'],
        trailerYouTubeId: 'oVzVdvGIC7U',
        duration: '36h 20m',
        genre: ['Crime', 'Drama'],
        shortDescription: 'A gangster family epic set in 1919 Birmingham, England, centered on a gang who sew razor blades in the peaks of their caps.',
        description: 'Peaky Blinders is a British period crime drama television series created by Steven Knight. Set in Birmingham, England, the series follows the exploits of the Shelby crime family in the direct aftermath of the First World War. The fictional family is loosely based on a real 19th-century urban youth gang of the same name, who were active in the city from the 1890s to the 1910s. The series stars Cillian Murphy as gang leader Thomas Shelby, Helen McCrory as Elizabeth "Polly" Gray, Paul Anderson as Arthur Shelby, and Sophie Rundle as Ada Shelby. The show has been praised for its writing, acting, cinematography, and stylish production.'
    },
    {
        title: '1917',
        image: '/1917.png',
        imageForTrends: '/1917-2.png',
        rating: 8.2,
        recommend: false,
        type: 'film',
        tags: ['popular'],
        trailerYouTubeId: 'YqNYrYUiMfg',
        duration: '1h 59m',
        genre: ['Drama', 'War'],
        shortDescription: 'Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory.',
        description: '1917 is a 2019 war film directed and produced by Sam Mendes, who co-wrote the screenplay with Krysty Wilson-Cairns. The film stars George MacKay, Dean-Charles Chapman, Mark Strong, Andrew Scott, Richard Madden, Claire Duburcq, Colin Firth, and Benedict Cumberbatch. It follows two young British soldiers during the First World War who are given a seemingly impossible mission: to deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldiers\' brothers, from walking straight into a deadly trap. The film is presented as if shot in a single continuous take, a technique that was praised by critics and earned the film numerous accolades.'
    },
    {
        title: 'The Last of Us',
        image: '/last-of-us.png',
        imageForTrends: '/last-of-us2.png',
        rating: 8.8,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'uLtkt8BonwM',
        duration: '9h 35m',
        genre: ['Action', 'Adventure', 'Drama'],
        shortDescription: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
        description: 'The Last of Us is an American post-apocalyptic drama television series created by Craig Mazin and Neil Druckmann for HBO. Based on the 2013 video game developed by Naughty Dog, the series is set twenty years after a mass fungal infection caused by a mutation in the genus Cordyceps, which sparked a global pandemic. The infection causes its victims to transform into zombie-like creatures and collapses society. The series follows Joel (Pedro Pascal), a smuggler tasked with escorting the immune teenager Ellie (Bella Ramsey) across a post-apocalyptic United States. The series has received widespread critical acclaim for its writing, performances, production values, and faithfulness to the source material.'
    },
    {
        title: 'Oppenheimer',
        image: '/oppenheimer.png',
        imageForTrends: '/oppenheimer2.png',
        rating: 8.3,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular', 'premiere'],
        trailerYouTubeId: 'bK6ldnjE3Y0',
        duration: '3h 0m',
        genre: ['Biography', 'Drama', 'History'],
        shortDescription: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
        description: 'Oppenheimer is a 2023 epic biographical thriller film written, directed, and produced by Christopher Nolan. It stars Cillian Murphy as J. Robert Oppenheimer, the American theoretical physicist who helped develop the first nuclear weapons as part of the Manhattan Project, and the film chronicles his life and career. Based on the 2005 biography American Prometheus by Kai Bird and Martin J. Sherwin, the film also features Emily Blunt as his wife Katherine "Kitty" Oppenheimer, Matt Damon as General Leslie Groves, Robert Downey Jr. as Lewis Strauss, and Florence Pugh as Jean Tatlock. The film is notable for its IMAX cinematography, practical effects, and non-linear narrative structure.'
    },
    {
        title: 'Wednesday',
        image: '/wednesday.png',
        imageForTrends: '/wednesday2.png',
        rating: 7.9,
        recommend: false,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'Di310WS8zLk',
        duration: '8h 45m',
        genre: ['Comedy', 'Crime', 'Fantasy'],
        shortDescription: 'Follows Wednesday Addams\' years as a student, when she attempts to master her emerging psychic ability.',
        description: 'Wednesday is an American coming-of-age supernatural comedy horror television series based on the character Wednesday Addams from The Addams Family. Created by Alfred Gough and Miles Millar, it stars Jenna Ortega as the titular character, with Gwendoline Christie, Riki Lindhome, Jamie McShane, Hunter Doohan, Percy Hynes White, Emma Myers, Joy Sunday, Georgie Farmer, Naomi J. Ogawa, Christina Ricci, and Moosa Mostafa appearing in supporting roles. The series follows Wednesday Addams as a student at the supernatural Nevermore Academy, where she attempts to master her emerging psychic ability, thwart a monstrous killing spree that has terrorized the local town, and solve the supernatural mystery that embroiled her parents 25 years ago.'
    },
    {
        title: 'Joker',
        image: '/joker.png',
        imageForTrends: '/joker2.png',
        rating: 8.4,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'zAGVQLHvwOY',
        duration: '2h 2m',
        genre: ['Crime', 'Drama', 'Thriller'],
        shortDescription: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.',
        description: 'Joker is a 2019 American psychological thriller film directed by Todd Phillips, who co-wrote the screenplay with Scott Silver. The film, based on DC Comics characters, stars Joaquin Phoenix as the Joker. An origin story set in 1981, it follows Arthur Fleck, a failed stand-up comedian whose descent into insanity and nihilism inspires a violent countercultural revolution against the wealthy in a decaying Gotham City. The film also stars Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Glenn Fleshler, Bill Camp, Shea Whigham, and Marc Maron. Joker received critical acclaim for Phoenix\'s performance and the film\'s exploration of mental illness and social inequality, though its dark tone and portrayal of violence sparked controversy.'
    },
    {
        title: 'Money Heist',
        image: '/money-heist.png',
        imageForTrends: '/money-heist2.png',
        rating: 8.2,
        recommend: true,
        type: 'serial',
        tags: ['trend', 'popular'],
        trailerYouTubeId: 'hMANIarjT50',
        duration: '43h 15m',
        genre: ['Action', 'Crime', 'Mystery'],
        shortDescription: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history.',
        description: 'Money Heist is a Spanish heist crime drama television series created by Álex Pina. The series traces two long-prepared heists led by the Professor (Álvaro Morte), one on the Royal Mint of Spain, and one on the Bank of Spain, told from the perspective of one of the robbers, Tokyo (Úrsula Corberó). The narrative is told in a real-time-like fashion and relies on flashbacks, time-jumps, hidden character motivations, and an unreliable narrator for complexity. The series subverts the heist genre by being told from the perspective of a woman, and it is noted for its sophisticated plot, interpersonal dramas, and direction. The series achieved worldwide popularity following the streaming of its original run on Netflix.'
    },
    {
        title: 'The Shawshank Redemption',
        image: '/shawshank.png',
        imageForTrends: '/shawshank2.png',
        rating: 9.3,
        recommend: true,
        type: 'film',
        tags: ['trend', 'popular'],
        trailerYouTubeId: '6hB3S9bIaco',
        duration: '2h 22m',
        genre: ['Drama'],
        shortDescription: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        description: 'The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. It tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money-laundering operation led by the prison warden Samuel Norton (Bob Gunton). The film explores themes of hope, friendship, and institutionalization, and has been praised for its storytelling, acting, and emotional impact.'
    }
]